buildscript {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.terraformersmc.com/releases' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.fabricmc:fabric-loom:1.1-SNAPSHOT'
    }
}

apply plugin: 'fabric-loom'
apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'base'  // required for archivesName

group = 'com.example'
version = '1.0.0'

base {
    archivesName.set("bossmusic")
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
    maven { url = 'https://maven.terraformersmc.com/releases' }
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.11'
    mappings 'net.fabricmc:yarn:1.21.11+build.1:v2'

    modImplementation 'net.fabricmc:fabric-loader:0.15.11'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.100.0+1.21.11'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
