plugins {
    id "net.fabricmc.fabric-loom-remap" version "1.14.0-alpha.31"
    id "maven-publish"
    id "java"
}

group = "com.example"
version = "1.0.0"
archivesBaseName = "bossmusic"

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings "net.fabricmc:yarn:1.21.11+build.1:v2"

    modImplementation "net.fabricmc:fabric-loader:0.15.11"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.100.0+1.21.11"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
}
